[package]
name = "memodis"
version = "0.1.0"
authors = ["imoyakin <imoyaki@outlook.com>"]
edition = "2018"

[dependencies]
toml = "*"
serde_derive = "*"
serde = "*"
lazy_static = "*"
crossbeam = "*"
chashmap = "2.2.2"